"""
ISLES'26 - Grand Challenge local test input preparation.

PURPOSE
    Build one input folder per rehearsal case, laid out exactly as Grand Challenge provisions
    /input at runtime. The platform sends one case per POST /invoke, so each case gets its own
    folder and the container is exercised once per folder.

    Two cases are recommended, chosen to cover the branches that differ at inference:
      - one with DAYS_POST_STROKE populated
      - one with DAYS_POST_STROKE null, which is the degenerate state a substantial share of
        the hidden test set is in

WHAT GRAND CHALLENGE PROVIDES AT RUNTIME
    /input/inputs.json            platform-generated, describes the active input sockets
    /input/stroke-metadata.json   the case metadata, values may be null
    /input/images/<slug>/<file>   the T1-weighted volume, one file only

    inputs.json is generated by the platform and is not part of the challenge data. It is
    synthesised here so that the local rehearsal reaches the same code path as the real run.
    Only socket.slug is read by inference.py; the real file carries further fields that the
    algorithm ignores.

PIPELINE / DATA FLOW
    holdout case (image path, optional metadata)
        |
        v
    [1] Copy the volume into images/<slug>/ WITHOUT altering it. The challenge delivers
        .nii.gz in native space, and the evaluation is computed in that same native space, so
        the rehearsal must start from the untouched file: any transcoding here would test a
        volume the platform will never send. A .mha or .mhd source is transcoded to .nii.gz
        only because it cannot otherwise be read by the nibabel-based shared contract.
        |
        v
    [2] Write stroke-metadata.json with the CENTER, DAYS_POST_STROKE and CHRONICITY fields.
        Note that the acquisition site key is named CENTER on the platform and SITE in the
        training CSV.
        |
        v
    [3] Write inputs.json declaring the two input sockets.
        |
        v
    test/input/<case_folder>/

USAGE
    python prepare_test_input.py \
        --output-root test/input \
        --case interf0:/path/sub-001_T1w.nii.gz:412 \
        --case interf0_case2:/path/sub-002_T1w.nii.gz:none

    Each --case is FOLDER:IMAGE_PATH:DAYS_POST_STROKE, where DAYS_POST_STROKE is an integer or
    the literal "none".

PREREQUISITES
    SimpleITK.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

import SimpleITK as sitk

# Input socket slug for the T1-weighted volume. The template documents t1-brain-mri; verify
# the value shown on the Interfaces tab of your algorithm page before submitting, since a
# mismatch produces an empty /input/images subtree at runtime.
T1_SLUG = "t1-brain-mri"
METADATA_SLUG = "stroke-metadata"

# Threshold, in days, separating the two chronicity classes used by the challenge metadata.
CHRONICITY_THRESHOLD_DAYS = 180


def write_case(
    case_dir: Path,
    image_path: Path,
    days_post_stroke: int | None,
    center: str,
) -> None:
    """
    Materialize one Grand-Challenge-shaped input folder.

    Inputs:
        case_dir        : destination folder, becomes /input inside the container
        image_path      : source T1-weighted volume
        days_post_stroke: days between onset and acquisition, or None for a missing value
        center          : acquisition site identifier
    Outputs:
        None. Three artefacts are written to disk.
    """
    image_dir = case_dir / "images" / T1_SLUG
    image_dir.mkdir(parents=True, exist_ok=True)

    # Exactly one image file must be present: the resolver takes the first match in
    # alphabetical order and a second file would be silently ignored.
    for stale in image_dir.glob("*"):
        stale.unlink()

    if image_path.name.endswith((".nii.gz", ".nii")):
        # Copied verbatim. The challenge test set is NIfTI in native space and the metrics are
        # computed on that grid, so the rehearsal must consume the untouched file.
        destination = image_dir / image_path.name
        shutil.copy2(image_path, destination)
    else:
        # A .mha or .mhd source cannot be read by nibabel, which the shared preprocessing
        # contract relies on. SimpleITK preserves spacing, origin and direction across the
        # conversion, so the native geometry is unchanged.
        destination = image_dir / f"{image_path.stem}.nii.gz"
        sitk.WriteImage(sitk.ReadImage(str(image_path)), str(destination), useCompression=True)

    # Report the native geometry. These four values are what the prediction must carry back:
    # the evaluation resamples nothing, so a mismatch on any of them invalidates every
    # voxel-wise metric. do_test_run_podman.sh compares the output against them.
    reference = sitk.ReadImage(str(destination))
    geometry = {
        "size": reference.GetSize(),
        "spacing": tuple(round(v, 5) for v in reference.GetSpacing()),
        "origin": tuple(round(v, 4) for v in reference.GetOrigin()),
        "direction": tuple(round(v, 4) for v in reference.GetDirection()),
    }

    chronicity = (
        None
        if days_post_stroke is None
        else int(days_post_stroke < CHRONICITY_THRESHOLD_DAYS)
    )
    metadata = {
        "CENTER": center,
        "DAYS_POST_STROKE": days_post_stroke,
        "CHRONICITY": chronicity,
    }
    with open(case_dir / "stroke-metadata.json", "w") as handle:
        json.dump(metadata, handle, indent=2)

    # Minimal inputs.json. The platform emits a richer structure, but inference.py only reads
    # socket.slug, so this is sufficient to exercise the interface resolution.
    inputs = [{"socket": {"slug": T1_SLUG}}, {"socket": {"slug": METADATA_SLUG}}]
    with open(case_dir / "inputs.json", "w") as handle:
        json.dump(inputs, handle, indent=2)

    print(f"{case_dir}: image={destination.name} days={days_post_stroke} chronicity={chronicity}")
    print(f"  native geometry: size={geometry['size']} spacing={geometry['spacing']} "
          f"origin={geometry['origin']}")


def parse_case(spec: str) -> tuple[str, Path, int | None]:
    """
    Parse a FOLDER:IMAGE_PATH:DAYS specification.

    Inputs:
        spec: colon-separated triple; DAYS is an integer or the literal "none"
    Outputs:
        (folder_name, image_path, days_post_stroke)
    Raises:
        ValueError: on a malformed specification or a missing image
    """
    parts = spec.rsplit(":", 2)
    if len(parts) != 3:
        raise ValueError(f"malformed --case {spec!r}, expected FOLDER:IMAGE_PATH:DAYS")

    folder, raw_path, raw_days = parts
    image_path = Path(raw_path)
    if not image_path.exists():
        raise ValueError(f"image not found: {image_path}")

    days = None if raw_days.strip().lower() in {"none", "null", "na", ""} else int(raw_days)
    return folder, image_path, days


def main() -> int:
    """Parse arguments and materialize every requested case folder."""
    parser = argparse.ArgumentParser(
        description="Build Grand-Challenge-shaped local test inputs."
    )
    parser.add_argument("--output-root", type=Path, default=Path("test/input"))
    parser.add_argument(
        "--case",
        action="append",
        required=True,
        help="FOLDER:IMAGE_PATH:DAYS, repeatable; DAYS may be an integer or 'none'",
    )
    parser.add_argument("--center", type=str, default="LOCAL_TEST")
    args = parser.parse_args()

    for spec in args.case:
        folder, image_path, days = parse_case(spec)
        write_case(args.output_root / folder, image_path, days, args.center)

    print(f"\nrehearse each case with:\n  CASE_DIR=<folder> ./do_test_run_podman.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())